apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/facebooc
  - ../base/instavote
patches:
  - facebooc-deploy-kustomization.yaml
  - instavote-deploy-kustomization.yaml
